# Generated by Django 5.0.4 on 2024-04-21 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0005_alter_platform_property_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='image',
            field=models.ImageField(blank=True, default='houses.png', upload_to=''),
        ),
    ]
